# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grafos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1556, 903)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(195, 50, 531, 201))
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.btnPintarGrafo = QtWidgets.QPushButton(self.centralwidget)
        self.btnPintarGrafo.setGeometry(QtCore.QRect(195, 270, 101, 31))
        self.btnPintarGrafo.setObjectName("btnPintarGrafo")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(40, 340, 751, 491))
        self.graphicsView.setObjectName("graphicsView")
        self.lblTtitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo.setGeometry(QtCore.QRect(200, 20, 461, 31))
        self.lblTtitulo.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo.setObjectName("lblTtitulo")
        self.lblTtitulo_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_3.setGeometry(QtCore.QRect(5, 90, 161, 31))
        self.lblTtitulo_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo_3.setObjectName("lblTtitulo_3")
        self.lblTtitulo2 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo2.setGeometry(QtCore.QRect(40, 340, 181, 71))
        self.lblTtitulo2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo2.setText("")
        self.lblTtitulo2.setPixmap(QtGui.QPixmap("logo_eafit_blanco.png"))
        self.lblTtitulo2.setObjectName("lblTtitulo2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 90, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.tabla_adyacen = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_adyacen.setGeometry(QtCore.QRect(830, 50, 531, 201))
        self.tabla_adyacen.setRowCount(4)
        self.tabla_adyacen.setColumnCount(4)
        self.tabla_adyacen.setObjectName("tabla_adyacen")
        self.lblTtitulo_4 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_4.setGeometry(QtCore.QRect(830, 10, 241, 31))
        self.lblTtitulo_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo_4.setObjectName("lblTtitulo_4")
        self.K2 = QtWidgets.QTableWidget(self.centralwidget)
        self.K2.setGeometry(QtCore.QRect(830, 330, 531, 201))
        self.K2.setRowCount(4)
        self.K2.setColumnCount(4)
        self.K2.setObjectName("K2")
        self.lblTtitulo_5 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_5.setGeometry(QtCore.QRect(830, 290, 241, 31))
        self.lblTtitulo_5.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo_5.setObjectName("lblTtitulo_5")
        self.K3 = QtWidgets.QTableWidget(self.centralwidget)
        self.K3.setGeometry(QtCore.QRect(830, 620, 531, 201))
        self.K3.setRowCount(4)
        self.K3.setColumnCount(4)
        self.K3.setObjectName("K3")
        self.lblTtitulo_6 = QtWidgets.QLabel(self.centralwidget)
        self.lblTtitulo_6.setGeometry(QtCore.QRect(830, 580, 241, 31))
        self.lblTtitulo_6.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 85, 255);")
        self.lblTtitulo_6.setObjectName("lblTtitulo_6")
        self.btn_adyacen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_adyacen.setGeometry(QtCore.QRect(1170, 260, 101, 31))
        self.btn_adyacen.setObjectName("btn_adyacen")
        self.btn_k2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_k2.setGeometry(QtCore.QRect(1170, 540, 101, 31))
        self.btn_k2.setObjectName("btn_k2")
        self.btn_k3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_k3.setGeometry(QtCore.QRect(1170, 830, 101, 31))
        self.btn_k3.setObjectName("btn_k3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(710, 160, 411, 551))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1556, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setToolTip(_translate("MainWindow", "Haga doble clic en el encabezado de un vértice para generar una matriz de pesos"))
        self.btnPintarGrafo.setText(_translate("MainWindow", "Dibujar Grafo"))
        self.lblTtitulo.setText(_translate("MainWindow", "Proyecto Final Grafos - Juan Manuel Lopera Soto"))
        self.lblTtitulo_3.setText(_translate("MainWindow", "Matriz de Pesos>>"))
        self.tabla_adyacen.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.lblTtitulo_4.setText(_translate("MainWindow", "Matriz de adyacencia"))
        self.K2.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.lblTtitulo_5.setText(_translate("MainWindow", "K2"))
        self.K3.setToolTip(_translate("MainWindow", "Haga doble clic en el cabaezado de un vértice para generar una matriz de pesos"))
        self.lblTtitulo_6.setText(_translate("MainWindow", "K3"))
        self.btn_adyacen.setText(_translate("MainWindow", "Calcular"))
        self.btn_k2.setText(_translate("MainWindow", "Calcular"))
        self.btn_k3.setText(_translate("MainWindow", "Calcular"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/d95ad0f4e197b1c92be27ed8212b235a.jpg\"/></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
